### ISSUE TITLE
dna ambiguity

### ISSUE THREAD

**Issue by biomendi** [feliixx/gotranseq#3]
Hi Feliixx, 

I have encountered an error when running gotranseq in my data. The error is the following:

```
WARNING: invalid char in sequence SAGAGTCATCTCCTATGCAGGCTGCCTGACTCAGATGTCTCTCTTTGCCATTTKTGGAGGCATGGAAGAGAGACATGCTCCTGAGTGTGATGGCCTATGGCCGGTTTGTAGCCATCTGTCACCCTCTATATCGTTCAGCCATCTTGAACCCATGTTTCTGTGGCTTCCTAGATTTGTTGTCTTCGTTTTGTTTTGTTTTGTTTTTCTCAGTCTTTTAGACTCCCAGCTGCACAACTTGATTGCCTTACAAATGACCGGCTTCAAGGATGTGGAATTCCTAATTTCTTCTGGGAACCTTCTCAACTCCCCATCTTGCATGTTGTGACACCTTCACCAGGAACATCAACCTGTATTTCCCTGCTGCCGTATTTGGTTTTCTTCCCATCTTGGGGACCTTTTCTCTTACTGTAAAATTGTTTCCTCCATTCTGAGGGTTTCATCATCAGGTGGGAAGTATAAACCTTCTCCACCTGTGGGTCTCACCTGCCAGTTGTTTGCTGATTTTGTGGAACAGGTGTTGGAGGGTACCTTGGTTCAGATGTGTCATCTTCCCCAAGAAAGAGTGCAGTGCCCTCAGTGATGTACCCGGTGGTCACCTCC: S, ignoringWARNING: invalid char in sequence SKTGGAGGCATGGAAGAGAGACATGCTCCTGAGTGTGATGGCCTATGGCCGGTTTGTAGCCATCTGTCACCCTCTATATCGTTCAGCCATCTTGAACCCATGTTTCTGTGGCTTCCTAGATTTGTTGTCTTCGTTTTGTTTTGTTTTGTTTTTCTCAGTCTTTTAGACTCCCAGCTGCACAACTTGATTGCCTTACAAATGACCGGCTTCAAGGATGTGGAATTCCTAATTTCTTCTGGGAACCTTCTCAACTCCCCATCTTGCATGTTGTGACACCTTCACCAGGAACATCAACCTGTATTTCCCTGCTGCCGTATTTGGTTTTCTTCCCATCTTGGGGACCTTTTCTCTTACTGTAAAATTGTTTCCTCCATTCTGAGGGTTTCATCATCAGGTGGGAAGTATAAACCTTCTCCACCTGTGGGTCTCACCTGCCAGTTGTTTGCTGATTTTGTGGAACAGGTGTTGGAGGGTACCTTGGTTCAGATGTGTCATCTTCCCCAAGAAAGAGTGCAGTGCCCTCAGTGATGTACCCGGTGGTCACCTCC: K, ignoringpanic: runtime error: index out of range [4915971] with length 263173

goroutine 21 [running]:
github.com/feliixx/gotranseq/transeq.(*writer).translate3Frames(0xc000980000, 0xc00005e600, 0x2f6, 0x5b6)
	/home/runner/work/gotranseq/gotranseq/transeq/writer.go:99 +0x89a
github.com/feliixx/gotranseq/transeq.(*writer).translate(0xc000980000, 0xc00005e600, 0x2f6, 0x5b6)
	/home/runner/work/gotranseq/gotranseq/transeq/writer.go:60 +0x71
github.com/feliixx/gotranseq/transeq.Translate.func1(0xc00010c150, 0xc000280000, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5858585858585800, 0x10fe62d, ...)
	/home/runner/work/gotranseq/gotranseq/transeq/transeq.go:149 +0x318
created by github.com/feliixx/gotranseq/transeq.Translate
	/home/runner/work/gotranseq/gotranseq/transeq/transeq.go:135 +0x3da
```
I think the reason is that there are ambiguous characters in my data. In this case, the character "S" represents the possibility of finding cytosine or guanine. Is there any solution to this issue?

Here are the nucleotide sequences in fasta format:

[test.fa.txt](https://github.com/feliixx/gotranseq/files/6142334/test.fa.txt)

**Comment by feliixx** [comment]
Hi @biomendi, thanks for the report

you're right, ambiguous nucleotides are curently not supported. However, the program should not crash. 
I've published a [new release](https://github.com/feliixx/gotranseq/releases/tag/v0.3.0) with a fix for this bug ( for now, ambiguous nucleotides are replaces with `N` ) 

I may add support for ambiguous nucleotide later, but I'm not sure how to do it yet
